// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=mocks/cache_mock.go -package=mocks Cache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entities "test_task/internal/entities"
	dto "test_task/pkg/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// DeleteTask mocks base method.
func (m *MockCache) DeleteTask(ctx context.Context, taskID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockCacheMockRecorder) DeleteTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockCache)(nil).DeleteTask), ctx, taskID)
}

// DeleteTasksByFilter mocks base method.
func (m *MockCache) DeleteTasksByFilter(ctx context.Context, taskID, teamID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasksByFilter", ctx, taskID, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasksByFilter indicates an expected call of DeleteTasksByFilter.
func (mr *MockCacheMockRecorder) DeleteTasksByFilter(ctx, taskID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasksByFilter", reflect.TypeOf((*MockCache)(nil).DeleteTasksByFilter), ctx, taskID, teamID)
}

// DeleteTasksByTeam mocks base method.
func (m *MockCache) DeleteTasksByTeam(ctx context.Context, teamID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasksByTeam", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasksByTeam indicates an expected call of DeleteTasksByTeam.
func (mr *MockCacheMockRecorder) DeleteTasksByTeam(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasksByTeam", reflect.TypeOf((*MockCache)(nil).DeleteTasksByTeam), ctx, teamID)
}

// GetTask mocks base method.
func (m *MockCache) GetTask(ctx context.Context, taskID int64) (*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, taskID)
	ret0, _ := ret[0].(*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockCacheMockRecorder) GetTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockCache)(nil).GetTask), ctx, taskID)
}

// GetTasksByFilter mocks base method.
func (m *MockCache) GetTasksByFilter(ctx context.Context, filter dto.TaskFilter) ([]*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByFilter", ctx, filter)
	ret0, _ := ret[0].([]*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByFilter indicates an expected call of GetTasksByFilter.
func (mr *MockCacheMockRecorder) GetTasksByFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByFilter", reflect.TypeOf((*MockCache)(nil).GetTasksByFilter), ctx, filter)
}

// GetTasksByTeam mocks base method.
func (m *MockCache) GetTasksByTeam(ctx context.Context, teamID int64) ([]*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByTeam", ctx, teamID)
	ret0, _ := ret[0].([]*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByTeam indicates an expected call of GetTasksByTeam.
func (mr *MockCacheMockRecorder) GetTasksByTeam(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByTeam", reflect.TypeOf((*MockCache)(nil).GetTasksByTeam), ctx, teamID)
}

// SetTask mocks base method.
func (m *MockCache) SetTask(ctx context.Context, task *entities.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTask indicates an expected call of SetTask.
func (mr *MockCacheMockRecorder) SetTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTask", reflect.TypeOf((*MockCache)(nil).SetTask), ctx, task)
}

// SetTasksByFilter mocks base method.
func (m *MockCache) SetTasksByFilter(ctx context.Context, filter dto.TaskFilter, tasks []*entities.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTasksByFilter", ctx, filter, tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTasksByFilter indicates an expected call of SetTasksByFilter.
func (mr *MockCacheMockRecorder) SetTasksByFilter(ctx, filter, tasks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTasksByFilter", reflect.TypeOf((*MockCache)(nil).SetTasksByFilter), ctx, filter, tasks)
}

// SetTasksByTeam mocks base method.
func (m *MockCache) SetTasksByTeam(ctx context.Context, teamID int64, tasks []*entities.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTasksByTeam", ctx, teamID, tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTasksByTeam indicates an expected call of SetTasksByTeam.
func (mr *MockCacheMockRecorder) SetTasksByTeam(ctx, teamID, tasks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTasksByTeam", reflect.TypeOf((*MockCache)(nil).SetTasksByTeam), ctx, teamID, tasks)
}

// Start mocks base method.
func (m *MockCache) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCacheMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCache)(nil).Start))
}

// Stop mocks base method.
func (m *MockCache) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockCacheMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCache)(nil).Stop), ctx)
}
