// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mocks/repository_mock.go -package=mocks Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	cases "test_task/internal/cases"
	entities "test_task/internal/entities"
	dto "test_task/pkg/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockRepository) AddComment(ctx context.Context, comment *entities.TaskComment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddComment indicates an expected call of AddComment.
func (mr *MockRepositoryMockRecorder) AddComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockRepository)(nil).AddComment), ctx, comment)
}

// AddHistoryRecord mocks base method.
func (m *MockRepository) AddHistoryRecord(ctx context.Context, record *entities.TaskHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHistoryRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddHistoryRecord indicates an expected call of AddHistoryRecord.
func (mr *MockRepositoryMockRecorder) AddHistoryRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHistoryRecord", reflect.TypeOf((*MockRepository)(nil).AddHistoryRecord), ctx, record)
}

// AddMember mocks base method.
func (m *MockRepository) AddMember(ctx context.Context, userID, teamID int64, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, userID, teamID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockRepositoryMockRecorder) AddMember(ctx, userID, teamID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockRepository)(nil).AddMember), ctx, userID, teamID, role)
}

// CreateTask mocks base method.
func (m *MockRepository) CreateTask(ctx context.Context, userID, assigneeID, teamID int64, title, description, status string) (*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, userID, assigneeID, teamID, title, description, status)
	ret0, _ := ret[0].(*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockRepositoryMockRecorder) CreateTask(ctx, userID, assigneeID, teamID, title, description, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockRepository)(nil).CreateTask), ctx, userID, assigneeID, teamID, title, description, status)
}

// CreateTeam mocks base method.
func (m *MockRepository) CreateTeam(ctx context.Context, name string, ownerID int64) (*entities.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, name, ownerID)
	ret0, _ := ret[0].(*entities.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockRepositoryMockRecorder) CreateTeam(ctx, name, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockRepository)(nil).CreateTeam), ctx, name, ownerID)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, name, email, hashPass string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, name, email, hashPass)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, name, email, hashPass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, name, email, hashPass)
}

// GetCommentsByTask mocks base method.
func (m *MockRepository) GetCommentsByTask(ctx context.Context, taskID int64, limit, offset int) ([]*entities.TaskComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsByTask", ctx, taskID, limit, offset)
	ret0, _ := ret[0].([]*entities.TaskComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsByTask indicates an expected call of GetCommentsByTask.
func (mr *MockRepositoryMockRecorder) GetCommentsByTask(ctx, taskID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsByTask", reflect.TypeOf((*MockRepository)(nil).GetCommentsByTask), ctx, taskID, limit, offset)
}

// GetInvalidAssigneeTasks mocks base method.
func (m *MockRepository) GetInvalidAssigneeTasks(ctx context.Context) ([]dto.InvalidAssigneeTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvalidAssigneeTasks", ctx)
	ret0, _ := ret[0].([]dto.InvalidAssigneeTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvalidAssigneeTasks indicates an expected call of GetInvalidAssigneeTasks.
func (mr *MockRepositoryMockRecorder) GetInvalidAssigneeTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvalidAssigneeTasks", reflect.TypeOf((*MockRepository)(nil).GetInvalidAssigneeTasks), ctx)
}

// GetMemberRole mocks base method.
func (m *MockRepository) GetMemberRole(ctx context.Context, userID, teamID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, userID, teamID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockRepositoryMockRecorder) GetMemberRole(ctx, userID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockRepository)(nil).GetMemberRole), ctx, userID, teamID)
}

// GetTaskByID mocks base method.
func (m *MockRepository) GetTaskByID(ctx context.Context, id int64) (*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, id)
	ret0, _ := ret[0].(*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockRepositoryMockRecorder) GetTaskByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockRepository)(nil).GetTaskByID), ctx, id)
}

// GetTaskHistory mocks base method.
func (m *MockRepository) GetTaskHistory(ctx context.Context, taskID int64, limit, offset int) ([]*entities.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistory", ctx, taskID, limit, offset)
	ret0, _ := ret[0].([]*entities.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistory indicates an expected call of GetTaskHistory.
func (mr *MockRepositoryMockRecorder) GetTaskHistory(ctx, taskID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistory", reflect.TypeOf((*MockRepository)(nil).GetTaskHistory), ctx, taskID, limit, offset)
}

// GetTasksByFilter mocks base method.
func (m *MockRepository) GetTasksByFilter(ctx context.Context, filter dto.TaskFilter) ([]*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByFilter", ctx, filter)
	ret0, _ := ret[0].([]*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByFilter indicates an expected call of GetTasksByFilter.
func (mr *MockRepositoryMockRecorder) GetTasksByFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByFilter", reflect.TypeOf((*MockRepository)(nil).GetTasksByFilter), ctx, filter)
}

// GetTasksByTeam mocks base method.
func (m *MockRepository) GetTasksByTeam(ctx context.Context, teamID int64, limit, offset int) ([]*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByTeam", ctx, teamID, limit, offset)
	ret0, _ := ret[0].([]*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByTeam indicates an expected call of GetTasksByTeam.
func (mr *MockRepositoryMockRecorder) GetTasksByTeam(ctx, teamID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByTeam", reflect.TypeOf((*MockRepository)(nil).GetTasksByTeam), ctx, teamID, limit, offset)
}

// GetTeamByID mocks base method.
func (m *MockRepository) GetTeamByID(ctx context.Context, id int64) (*entities.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByID", ctx, id)
	ret0, _ := ret[0].(*entities.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByID indicates an expected call of GetTeamByID.
func (mr *MockRepositoryMockRecorder) GetTeamByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByID", reflect.TypeOf((*MockRepository)(nil).GetTeamByID), ctx, id)
}

// GetTeamMembers mocks base method.
func (m *MockRepository) GetTeamMembers(ctx context.Context, teamID int64) ([]*entities.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamMembers", ctx, teamID)
	ret0, _ := ret[0].([]*entities.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamMembers indicates an expected call of GetTeamMembers.
func (mr *MockRepositoryMockRecorder) GetTeamMembers(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamMembers", reflect.TypeOf((*MockRepository)(nil).GetTeamMembers), ctx, teamID)
}

// GetTeamStats mocks base method.
func (m *MockRepository) GetTeamStats(ctx context.Context) ([]dto.TeamStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamStats", ctx)
	ret0, _ := ret[0].([]dto.TeamStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamStats indicates an expected call of GetTeamStats.
func (mr *MockRepositoryMockRecorder) GetTeamStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamStats", reflect.TypeOf((*MockRepository)(nil).GetTeamStats), ctx)
}

// GetTeamsByIDs mocks base method.
func (m *MockRepository) GetTeamsByIDs(ctx context.Context, ids []int64) ([]*entities.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamsByIDs", ctx, ids)
	ret0, _ := ret[0].([]*entities.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamsByIDs indicates an expected call of GetTeamsByIDs.
func (mr *MockRepositoryMockRecorder) GetTeamsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamsByIDs", reflect.TypeOf((*MockRepository)(nil).GetTeamsByIDs), ctx, ids)
}

// GetTopCreators mocks base method.
func (m *MockRepository) GetTopCreators(ctx context.Context) ([]dto.TopCreator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCreators", ctx)
	ret0, _ := ret[0].([]dto.TopCreator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCreators indicates an expected call of GetTopCreators.
func (mr *MockRepositoryMockRecorder) GetTopCreators(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCreators", reflect.TypeOf((*MockRepository)(nil).GetTopCreators), ctx)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockRepository) GetUserByID(ctx context.Context, id int64) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepository)(nil).GetUserByID), ctx, id)
}

// GetUserTeams mocks base method.
func (m *MockRepository) GetUserTeams(ctx context.Context, userID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTeams", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTeams indicates an expected call of GetUserTeams.
func (mr *MockRepositoryMockRecorder) GetUserTeams(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTeams", reflect.TypeOf((*MockRepository)(nil).GetUserTeams), ctx, userID)
}

// InTx mocks base method.
func (m *MockRepository) InTx(ctx context.Context, fn func(context.Context, cases.Repository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTx indicates an expected call of InTx.
func (mr *MockRepositoryMockRecorder) InTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTx", reflect.TypeOf((*MockRepository)(nil).InTx), ctx, fn)
}

// IsAdminOrOwner mocks base method.
func (m *MockRepository) IsAdminOrOwner(ctx context.Context, userID, teamID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdminOrOwner", ctx, userID, teamID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdminOrOwner indicates an expected call of IsAdminOrOwner.
func (mr *MockRepositoryMockRecorder) IsAdminOrOwner(ctx, userID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdminOrOwner", reflect.TypeOf((*MockRepository)(nil).IsAdminOrOwner), ctx, userID, teamID)
}

// IsMember mocks base method.
func (m *MockRepository) IsMember(ctx context.Context, userID, teamID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, userID, teamID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockRepositoryMockRecorder) IsMember(ctx, userID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockRepository)(nil).IsMember), ctx, userID, teamID)
}

// Ping mocks base method.
func (m *MockRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), ctx)
}

// Start mocks base method.
func (m *MockRepository) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRepositoryMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRepository)(nil).Start))
}

// Stop mocks base method.
func (m *MockRepository) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRepositoryMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRepository)(nil).Stop), ctx)
}

// UpdateTask mocks base method.
func (m *MockRepository) UpdateTask(ctx context.Context, task *entities.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockRepositoryMockRecorder) UpdateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockRepository)(nil).UpdateTask), ctx, task)
}
