// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entities "test_task/internal/entities"
	dto "test_task/pkg/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockService) AddComment(ctx context.Context, userID, taskID int64, content string) (*entities.TaskComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", ctx, userID, taskID, content)
	ret0, _ := ret[0].(*entities.TaskComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddComment indicates an expected call of AddComment.
func (mr *MockServiceMockRecorder) AddComment(ctx, userID, taskID, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockService)(nil).AddComment), ctx, userID, taskID, content)
}

// AddMember mocks base method.
func (m *MockService) AddMember(ctx context.Context, userID, teamID, memberID int64, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, userID, teamID, memberID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockServiceMockRecorder) AddMember(ctx, userID, teamID, memberID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockService)(nil).AddMember), ctx, userID, teamID, memberID, role)
}

// CreateTask mocks base method.
func (m *MockService) CreateTask(ctx context.Context, userID, assigneeID, teamID int64, title, description string) (*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, userID, assigneeID, teamID, title, description)
	ret0, _ := ret[0].(*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockServiceMockRecorder) CreateTask(ctx, userID, assigneeID, teamID, title, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockService)(nil).CreateTask), ctx, userID, assigneeID, teamID, title, description)
}

// CreateTeam mocks base method.
func (m *MockService) CreateTeam(ctx context.Context, userID int64, name string) (*entities.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, userID, name)
	ret0, _ := ret[0].(*entities.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockServiceMockRecorder) CreateTeam(ctx, userID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockService)(nil).CreateTeam), ctx, userID, name)
}

// CreateUser mocks base method.
func (m *MockService) CreateUser(ctx context.Context, name, email, password string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, name, email, password)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockServiceMockRecorder) CreateUser(ctx, name, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockService)(nil).CreateUser), ctx, name, email, password)
}

// GetCommentsByTask mocks base method.
func (m *MockService) GetCommentsByTask(ctx context.Context, taskID int64, limit, offset int) ([]*entities.TaskComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsByTask", ctx, taskID, limit, offset)
	ret0, _ := ret[0].([]*entities.TaskComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsByTask indicates an expected call of GetCommentsByTask.
func (mr *MockServiceMockRecorder) GetCommentsByTask(ctx, taskID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsByTask", reflect.TypeOf((*MockService)(nil).GetCommentsByTask), ctx, taskID, limit, offset)
}

// GetInvalidAssigneeTasks mocks base method.
func (m *MockService) GetInvalidAssigneeTasks(ctx context.Context) ([]dto.InvalidAssigneeTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvalidAssigneeTasks", ctx)
	ret0, _ := ret[0].([]dto.InvalidAssigneeTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvalidAssigneeTasks indicates an expected call of GetInvalidAssigneeTasks.
func (mr *MockServiceMockRecorder) GetInvalidAssigneeTasks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvalidAssigneeTasks", reflect.TypeOf((*MockService)(nil).GetInvalidAssigneeTasks), ctx)
}

// GetTaskByID mocks base method.
func (m *MockService) GetTaskByID(ctx context.Context, taskID int64) (*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, taskID)
	ret0, _ := ret[0].(*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockServiceMockRecorder) GetTaskByID(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockService)(nil).GetTaskByID), ctx, taskID)
}

// GetTaskHistory mocks base method.
func (m *MockService) GetTaskHistory(ctx context.Context, taskID int64, limit, offset int) ([]*entities.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistory", ctx, taskID, limit, offset)
	ret0, _ := ret[0].([]*entities.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistory indicates an expected call of GetTaskHistory.
func (mr *MockServiceMockRecorder) GetTaskHistory(ctx, taskID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistory", reflect.TypeOf((*MockService)(nil).GetTaskHistory), ctx, taskID, limit, offset)
}

// GetTasksByFilter mocks base method.
func (m *MockService) GetTasksByFilter(ctx context.Context, userID int64, filter dto.TaskFilter) ([]*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByFilter", ctx, userID, filter)
	ret0, _ := ret[0].([]*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByFilter indicates an expected call of GetTasksByFilter.
func (mr *MockServiceMockRecorder) GetTasksByFilter(ctx, userID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByFilter", reflect.TypeOf((*MockService)(nil).GetTasksByFilter), ctx, userID, filter)
}

// GetTasksByTeam mocks base method.
func (m *MockService) GetTasksByTeam(ctx context.Context, teamID int64, limit, offset int) ([]*entities.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByTeam", ctx, teamID, limit, offset)
	ret0, _ := ret[0].([]*entities.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByTeam indicates an expected call of GetTasksByTeam.
func (mr *MockServiceMockRecorder) GetTasksByTeam(ctx, teamID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByTeam", reflect.TypeOf((*MockService)(nil).GetTasksByTeam), ctx, teamID, limit, offset)
}

// GetTeamByID mocks base method.
func (m *MockService) GetTeamByID(ctx context.Context, teamID int64) (*entities.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByID", ctx, teamID)
	ret0, _ := ret[0].(*entities.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByID indicates an expected call of GetTeamByID.
func (mr *MockServiceMockRecorder) GetTeamByID(ctx, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByID", reflect.TypeOf((*MockService)(nil).GetTeamByID), ctx, teamID)
}

// GetTeamMembers mocks base method.
func (m *MockService) GetTeamMembers(ctx context.Context, teamID int64) ([]*entities.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamMembers", ctx, teamID)
	ret0, _ := ret[0].([]*entities.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamMembers indicates an expected call of GetTeamMembers.
func (mr *MockServiceMockRecorder) GetTeamMembers(ctx, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamMembers", reflect.TypeOf((*MockService)(nil).GetTeamMembers), ctx, teamID)
}

// GetTeamStats mocks base method.
func (m *MockService) GetTeamStats(ctx context.Context) ([]dto.TeamStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamStats", ctx)
	ret0, _ := ret[0].([]dto.TeamStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamStats indicates an expected call of GetTeamStats.
func (mr *MockServiceMockRecorder) GetTeamStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamStats", reflect.TypeOf((*MockService)(nil).GetTeamStats), ctx)
}

// GetTeams mocks base method.
func (m *MockService) GetTeams(ctx context.Context, userID int64) ([]dto.TeamWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeams", ctx, userID)
	ret0, _ := ret[0].([]dto.TeamWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeams indicates an expected call of GetTeams.
func (mr *MockServiceMockRecorder) GetTeams(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeams", reflect.TypeOf((*MockService)(nil).GetTeams), ctx, userID)
}

// GetTopCreators mocks base method.
func (m *MockService) GetTopCreators(ctx context.Context) ([]dto.TopCreator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCreators", ctx)
	ret0, _ := ret[0].([]dto.TopCreator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCreators indicates an expected call of GetTopCreators.
func (mr *MockServiceMockRecorder) GetTopCreators(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCreators", reflect.TypeOf((*MockService)(nil).GetTopCreators), ctx)
}

// GetUserByEmail mocks base method.
func (m *MockService) GetUserByEmail(ctx context.Context, email string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockServiceMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockService)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockService) GetUserByID(ctx context.Context, id int64) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockServiceMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockService)(nil).GetUserByID), ctx, id)
}

// Login mocks base method.
func (m *MockService) Login(ctx context.Context, email, password string) (*entities.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockServiceMockRecorder) Login(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockService)(nil).Login), ctx, email, password)
}

// UpdateTask mocks base method.
func (m *MockService) UpdateTask(ctx context.Context, userID int64, task *entities.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, userID, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockServiceMockRecorder) UpdateTask(ctx, userID, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockService)(nil).UpdateTask), ctx, userID, task)
}
