http:
  port: 8080
  timeout: 3s
storage:
  connection_string: root:1124@tcp(localhost:3306)/taskmanager?parseTime=true&charset=utf8mb4
  max_conns: 25
  max_idle_conns: 5
  time_life_conns: 1m
  time_life_idle_conns: 5m
logger:
  level: info
  add_source: true
metrics:
  port: 8083
  timeout: 3s
gracefull_shutdown:
  timeout: 5s
token:
  secret: my-super-secret-key
  duration: 24h